### PR TITLE
WIP - Report uploading playground PR

### PR DESCRIPTION
**Pull request by paveljandejsek**

### CODE REVIEW

**Comment by paveljandejsek** [comment]
Hello world

**Comment by paveljandejsek** [comment]
Reports: reports.zip

**Comment by paveljandejsek** [comment]
Reports: [reports.zip](https://transfer.sh/KFHTq/reports.zip)

**Comment by mbocek** [comment]
Not feasible

**Comment by paveljandejsek** [comment]
Generated [reports](http://www.gdtorrent.com/jbus-reports/83)

**Comment by paveljandejsek** [comment]
Generated [reports](http://www.gdtorrent.com/jbus-reports/83)

**Comment by paveljandejsek** [comment]
Generated [reports](http://sal07.vas-server.cz/jrs/83)

**Pull request closed without merging**
