### PR TITLE
Fixed saving of rest headers from response if body is empty.

### LINKED ISSUE #541: Rest step savig response fails
When there is no response body, and user tryes to save headers, stepm fails:

String response = testContext.get(REST_RESPONSE_JSON).toString();
HttpHeaders headers = testContext.get(REST_RESPONSE_HEADERS);

Cannot invoke "Object.toString()" because the return value of "org.jbehavesupport.core.TestContext.get(String)" is null

### PR DESCRIPTION
**Pull request by paveljandejsek**
Closes #541

### CODE REVIEW

**Review by xsmrcek — APPROVED** [review]

**Comment by paveljandejsek** [comment]
Question - do we want to fail or return null when header that is not present is being saved? Current fix makes the value being saved in context null (instead of previous NPE)

**Comment by thradec** [comment]
I'd say, it should behave the same way as for saving parts of the response body, when the path is missing.

**Comment by paveljandejsek** [comment]
> I'd say, it should behave the same way as for saving parts of the response body, when the path is missing.

Good point, currently we do not solve it on our side and let json path implementation handle it, eg:
`com.jayway.jsonpath.PathNotFoundException: No results for path: $['asdName']`

So I added assert to the headers... Do we want to add assert to json path as well (to keep the exceptions the same?)

**Comment by thradec** [comment]
> Do we want to add assert to json path as well (to keep the exceptions the same?)

I think it is not necessary.

**Review by thradec — APPROVED** [review]

**Pull request merged**
