### PR TITLE
Java 11 compatibility fixes

### PR DESCRIPTION
**Pull request by paveljandejsek**
Solves #106 

Added openjdk11 to travis

### CODE REVIEW

**Comment by paveljandejsek** [comment]
Does anyone know why travis does the builds 207.2 and 207.3?:
https://travis-ci.org/EmbedITCZ/jbehave-support/builds/522705401

I would expect two builds for each stage with different JDK, but this build output for our config confuses me 😮

**Comment by mbocek** [comment]
Looks like the matrix definition is the right solution. Check https://github.com/lihaoyi/mill/blob/master/.travis.yml

Hopefully, it will work.

**Comment by paveljandejsek** [comment]
> Looks like the matrix definition is the right solution. Check https://github.com/lihaoyi/mill/blob/master/.travis.yml
> 
> Hopefully, it will work.

It should work, but any idea how to avoid copy pasting our whole mvn+other commands for every matrix record? (i.e. clean install two times, test + codacy two times, verify + codacy two times) 
Apart from putting it into separate .sh file that would get added into git (which is what the example does but at least I personally do not want to go that way unless there is no better option)

**Comment by mbocek** [comment]
> > Looks like the matrix definition is the right solution. Check https://github.com/lihaoyi/mill/blob/master/.travis.yml
> > Hopefully, it will work.
> 
> It should work, but any idea how to avoid copy pasting our whole mvn+other commands for every matrix record? (i.e. clean install two times, test + codacy two times, verify + codacy two times)
> Apart from putting it into separate .sh file that would get added into git (which is what the example does but at least I personally do not want to go that way unless there is no better option)

No Idea... based on docu it should work by default. Just an idea: try to explicitly add jdk under each stage section.

**Comment by paveljandejsek** [comment]
> > > Looks like the matrix definition is the right solution. Check https://github.com/lihaoyi/mill/blob/master/.travis.yml
> > > Hopefully, it will work.
> > 
> > 
> > It should work, but any idea how to avoid copy pasting our whole mvn+other commands for every matrix record? (i.e. clean install two times, test + codacy two times, verify + codacy two times)
> > Apart from putting it into separate .sh file that would get added into git (which is what the example does but at least I personally do not want to go that way unless there is no better option)
> 
> No Idea... based on docu it should work by default. Just an idea: try to explicitly add jdk under each stage section.

Doesn't seem to do a thing 😕 After lots of trial and error I am slowly starting to think that we will either need to repeat the commands twice or to extract them into external .sh files... (unless someone comes up with a better solution that I am missing 🙂)

**Comment by paveljandejsek** [comment]
Please check and comment, once travis fixes [openjdk11 issues](https://github.com/TweetWallFX/TweetwallFX/issues/765), this PR should be good to go.

I copy pasted the stages twice in travis - not particularly happy with this, but apart of extracting the commands to external scripts that would become part of git repo this was the only solution I got working to build all stages on two JDKs

**Comment by paveljandejsek** [comment]
Btw. As far as Travis goes - do we have a reason to stay on Trusty (end of standard support this month AFAIK) or should I try to migrate to Xenial?

**Comment by paveljandejsek** [comment]
Ok taking previously said back - right now SNAFU, it seems like we will have to use two different distros for each java and I will also have to take a closer look at the commands as well 🤕

**Comment by paveljandejsek** [comment]
Ok, should finally be working :slightly_smiling_face: 
Some notes:
- Due to Travis bugs/features we are building 8/11 on different Ubuntu versions
- Build commands were moved to external scripts in ci folder - due to problems with passing of strings and some special shell characters such as `&()`
- For java 8 we are using oracle jdk, for 11 openjdk

Please review (and when merging please squash commits into one)

**Comment by mbocek** [comment]
Please add to release profile enforce to JDK8.

**Comment by paveljandejsek** [comment]
Rebased, squashed, added jdk8 enforce - happy merging 🙂

**Pull request merged**
