### PR TITLE
Loading screenshots from custom directory to xml reports

### PR DESCRIPTION
**Pull request by Hebcak**
The path to a screenshot is now written to the xml, not just the file name.

### CODE REVIEW

**Comment by paveljandejsek** [comment]
Generated [reports](http://95.168.205.146:8080/reports/181/index.xml)

**Comment by paveljandejsek** [comment]
Generated [reports](http://95.168.205.146:8080/reports/181/index.xml)

**Comment by Hebcak** [comment]
Added support for fail screenshots. Example report with custom screenshot directory:
[target.zip](https://github.com/EmbedITCZ/jbehave-support/files/3545544/target.zip)

**Comment by paveljandejsek** [comment]
Generated [reports](http://95.168.205.146:8080/reports/181/index.xml)

**Pull request merged**
