### PR TITLE
Calling xslt templates by name, not match

### PR DESCRIPTION
**Pull request by Hebcak**
If user wanted to use his own reporter, his own tags won`t collide with ours

### CODE REVIEW

**Comment by paveljandejsek** [comment]
Generated [reports](http://95.168.205.146:8080/reports/168/index.xml)

**Comment by Hebcak** [comment]
Checked the generated reports and found no problems. Can you please give me some steps to reproduce this issue?

> Please check generated reports and do something about this:
> image

**Comment by AmyKosinova** [comment]
Well, generated reports attached to this PR looks malformed same way @xsmrcek illustrated.
Moreover navigation from report to other report doesn't work 
> image

Please double check all functionality of report.

**Comment by paveljandejsek** [comment]
> Well, generated reports attached to this PR looks malformed same way @xsmrcek illustrated.
> Moreover navigation from report to other report doesn't work
> 
> Please double check all functionality of report.

FYI - Caused by browser of choice (Safari works, Chrome behaves as @AmyKosinova and @xsmrcek mentioned)

**Comment by xsmrcek** [comment]
> > Well, generated reports attached to this PR looks malformed same way @xsmrcek illustrated.
> > Moreover navigation from report to other report doesn't work
> > Please double check all functionality of report.
> 
> FYI - Caused by browser of choice (Safari works, Chrome behaves as @AmyKosinova and @xsmrcek mentioned)

Please check functionality of MS browsers too. MS Edge and IE are most used browsers to check reports in my team. (as chrome don't load reports from local drive).

**Comment by paveljandejsek** [comment]
Generated [reports](http://95.168.205.146:8080/reports/168/index.xml)

**Comment by paveljandejsek** [comment]
Generated [reports](http://95.168.205.146:8080/reports/168/index.xml)

**Pull request merged**
